# Generated by Django 2.2.3 on 2019-07-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='station.Station'),
        ),
    ]
