# Generated by Django 2.2.3 on 2019-07-21 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_auto_20190720_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
