# Generated by Django 2.2.3 on 2019-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_station_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_value',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(default='C', max_length=7),
            preserve_default=False,
        ),
    ]
