# Generated by Django 2.2.3 on 2019-07-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_auto_20190722_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ['date']},
        ),
    ]
